version: '3'

services:
  cbme:
    image: christianbaer.me
    container_name: christianbaer_me
    build:
      context: https://github.com/chrisb86/christianbaer.me.git
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.cbme.rule=Host(`christianbaer.me`)
      - traefik.http.routers.cbme.entrypoints=https
      - traefik.http.routers.cbme.tls.certresolver=inwx
      - traefik.http.routers.cbme.middlewares=secured@file
      - traefik.http.routers.cbme.tls.options=modern@file
      - traefik.http.services.cbme.loadbalancer.server.port=8080
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
